### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by schmunk42** [gusnips/yii.translate#1]
Hi, we just wanted to let you know, that we did some enhancements, see https://github.com/Quexer69/yii.translate/compare

Let us know if your extension is still under development and if you'd like a PR for these changes, otherwise, we'll continue development in our fork.

Best regards,
schmunk

**Comment by gusnips** [comment]
Hey Tobias

Thanks. I like what you did there.

It's not under development, but it might change in the future in case I need to do changes on it.

The changes to use Yii Boostrap would break BC. I always use but not everyone. Also the way you did it bootstrap/widgets would have to be added to Yii import path.

Anyway, thanks for letting me know and great job!

Cheers,
Gustavo

**Comment by schmunk42** [comment]
btw: We've added a dependency in [composer.json](https://github.com/Quexer69/yii.translate/blob/master/composer.json) Actually it's yiibooster, but it should be compatible with yii-bootstrap. Sure, there should be also an entry in the README how to enable it in your app.

You could also release a 2.0.0-dev.1 to indicate the API change.

Let me know if you'd like to do so, otherwise I'll setup a fork for my composer projects. Thanks!

**Comment by gusnips** [comment]
Hey schmunk
Please update the readme on installation notes and do the push
Or I can add you as collaborator

Thanks a lot!

Gustavo
