### ISSUE TITLE
 Pagination is not showing

### ISSUE THREAD

**Issue by traprajith** [gusnips/yii.translate#6]
I replaced the file components/MPTranslate.php from the latest release , but the pagination still not working.

**Comment by gusnips** [comment]
It only fixed the pagination counter that editLink page has, it doesn't add it to missinkLink page

**Comment by traprajith** [comment]
actually its a major issue!!

**Comment by gusnips** [comment]
Ok. I might have overlooked. What database are you using?

**Comment by traprajith** [comment]
mysql
